### PR TITLE
Disable `Shape::Command` only when `wasm-bindgen` feature is used

### LINKED ISSUE #40: Why is `Shape::Command` disabled on wasm?
I'm developing a project that is compiled to wasm (cloudflare worker) and needs to generate qr codes with custom visual processing when converting to an image. I've completed the processing using the command shape variant, but now I need to use it in wasm.

Why is it disabled for wasm? I don't think there are any issues preventing it being enabled, as it's just a function pretty much.

An explanation would be appreciated, or a patch to remove the disabling on wasm arch.

### PR DESCRIPTION
**Pull request by JohnTheCoolingFan**
Fixes #40 

Changed `cfg` and `cfg_attr` attributes to do changes that conflict with exposing the api to wasm only when wasm-bindgen is enabled so that teh library can be used in projects compiled for wasm which do not need wasm-bindgen for this crate.

### CODE REVIEW

**Comment by erwanvivien** [comment]
Hey, I'll look into this today, same for your other PR!
Thanks :)

**Comment by erwanvivien** [comment]
I'm curious, how do you build your Wasm file? I'd like to try the PR
I ran `cargo r --target wasm32-unknown-unknown -Fimage --example image` that did not work

**Comment by JohnTheCoolingFan** [comment]
Try reading the error. On my end thsi command gives an error in criterion because it's one of the dev dependencies. I'll see if rayon feature can be turned off for wasm target.

**Comment by erwanvivien** [comment]
So you're using the same command?

**Comment by JohnTheCoolingFan** [comment]
I tested the PR by building a project that depends on the lib. I now see that I overlooked that exampels also need to run and this was not an obvious issue

**Comment by erwanvivien** [comment]
You're only using the svg feature in your project, right?

**Comment by JohnTheCoolingFan** [comment]
No, I'm using image as well

**Comment by erwanvivien** [comment]
👌

**Comment by JohnTheCoolingFan** [comment]
Hmm, that buidl error is weird. I thought cfg attrs worked on enum variants, looks like they don't

**Comment by JohnTheCoolingFan** [comment]
Ah, yes: https://github.com/rustwasm/wasm-bindgen/issues/3297

**Comment by erwanvivien** [comment]
Thanks a lot @JohnTheCoolingFan

**Comment by JohnTheCoolingFan** [comment]
Yes, an update on crates.io would be very welcome

**Comment by erwanvivien** [comment]
Will do soon :)

**Comment by erwanvivien** [comment]
Hey @JohnTheCoolingFan, 0.10.3 is up now :)

**Pull request merged**
