### PR TITLE
Allow QRBuilder to accept bytes

### PR DESCRIPTION
**Pull request by parasyte**
QR codes should not be limited to storing only UTF-8 encoded text. Raw bytes are more useful.

Strings and string slices can trivially by converted to a vector of bytes. This is a breaking change, but also a great ergonomic and functionality improvement.

### CODE REVIEW

**Comment by erwanvivien** [comment]
Thanks for your contribution, I believe this is indeed a good idea! I will probably make it a 0.8.0 release.

**Comment by erwanvivien** [comment]
Do you have some modification to do before merge ?

**Comment by parasyte** [comment]
I think I'm done with changes now. I noticed a few other uses of `into()` that I missed on the first round. But it looks good to me now. Please double check.

**Comment by erwanvivien** [comment]
I did double check, and it seems fine to me, merging

**Comment by erwanvivien** [comment]
@parasyte [crates.io](https://crates.io/crates/fast_qr) is up-to-date :)

**Pull request merged**
